services:
  - type: web
    name: task-manager-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-frontend-url.netlify.app
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
